[mypy]
python_version = 3.13
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = False
disallow_untyped_defs = False
exclude = [
    tests/,
    scripts/,
    .venv/,
    __pycache__,
    core/providers/_proxy_server_router_new_DEPRECATED.py,
]
strict_optional = False
