"""AgentHarness Inbox Watcher — runs inside the agent's environment.

Watches:
  - alerts_inbox.jsonl for new alerts
  - briefings/ for new briefing files
  - proposals/ for new pending proposals

Delivers via Telegram using the AGENT's bot token (not AgentHarness's).
Marks alerts as delivered after sending.

This file is GENERATED by `agentharness generate-agent-plugin`.
It is meant to be installed in the agent's environment, not run from AgentHarness.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
import urllib.request
import urllib.parse
from pathlib import Path
from datetime import datetime

log = logging.getLogger("inbox_watcher")


class InboxWatcher:
    def __init__(self, inbox_dir: str, telegram_token: str, telegram_chat_id: str):
        self.inbox_dir = Path(inbox_dir)
        self.telegram_token = telegram_token
        self.telegram_chat_id = telegram_chat_id

    def check_alerts(self) -> int:
        """Check for undelivered alerts, send via Telegram, mark delivered."""
        alerts_file = self.inbox_dir / "alerts_inbox.jsonl"
        if not alerts_file.exists():
            return 0

        try:
            alerts = json.loads(alerts_file.read_text())
        except (json.JSONDecodeError, OSError):
            return 0

        if not isinstance(alerts, list):
            return 0

        sent = 0
        for alert in alerts:
            if alert.get("delivered"):
                continue
            
            message = alert.get("message", "")
            # Silence transient LLM errors/fallbacks
            if any(kw in message.lower() for kw in ["429", "rate limit", "switching to fallback", "quota exceeded"]):
                alert["delivered"] = True
                sent += 1
                continue

            severity = alert.get("severity", "info").upper()
            source = alert.get("source", "")
            text = f"[{severity}] {message}"
            if source:
                text += f"\n(from: {source})"

            if self._send_telegram(text):
                alert["delivered"] = True
                sent += 1

        if sent > 0:
            alerts_file.write_text(json.dumps(alerts, indent=2))
        return sent

    def check_briefings(self) -> int:
        """Check for new briefing files, send summary via Telegram."""
        briefings_dir = self.inbox_dir / "briefings"
        if not briefings_dir.is_dir():
            return 0

        sent = 0
        for f in sorted(briefings_dir.glob("*.json")):
            marker = f.with_suffix(".delivered")
            if marker.exists():
                continue
            try:
                briefing = json.loads(f.read_text())
                text = self._format_briefing(briefing)
                if self._send_telegram(text):
                    marker.touch()
                    sent += 1
            except (json.JSONDecodeError, OSError):
                continue
        return sent


    def check_proposals(self) -> int:
        """Check for new pending proposals, notify via Telegram."""
        proposals_dir = self.inbox_dir / "proposals"
        if not proposals_dir.is_dir():
            return 0

        sent = 0
        for f in sorted(proposals_dir.glob("*.json")):
            try:
                proposal = json.loads(f.read_text())
                if proposal.get("status") != "pending":
                    continue
                if proposal.get("notified"):
                    continue

                pid = proposal.get("proposal_id", "?")
                tool = proposal.get("tool_name", "?")
                reason = proposal.get("reason", "")
                text = f"Proposal #{pid}: {tool}\nReason: {reason}\n\nReply: approve {pid} / reject {pid}"

                if self._send_telegram(text):
                    proposal["notified"] = True
                    f.write_text(json.dumps(proposal, indent=2))
                    sent += 1
            except (json.JSONDecodeError, OSError):
                continue
        return sent


    def tick(self) -> dict:
        """Run one check cycle."""
        alerts = self.check_alerts()
        briefings = self.check_briefings()
        proposals = self.check_proposals()
        return {"alerts_sent": alerts, "briefings_sent": briefings, "proposals_sent": proposals}

    def run_loop(self, interval: int = 60):
        """Run continuously, checking every interval seconds."""
        log.info(f"Inbox watcher started. Checking {self.inbox_dir} every {interval}s")
        while True:
            try:
                result = self.tick()
                total = sum(result.values())
                if total > 0:
                    log.info(f"Delivered: {result}")
            except Exception as e:
                log.error(f"Tick error: {e}")
            time.sleep(interval)

    def _send_telegram(self, text: str) -> bool:
        """Send a message via Telegram Bot API. Uses urllib (no dependencies)."""
        if not self.telegram_token or not self.telegram_chat_id:
            log.warning("Telegram credentials not configured")
            return False
        try:
            url = f"https://api.telegram.org/bot{self.telegram_token}/sendMessage"
            data = urllib.parse.urlencode({
                "chat_id": self.telegram_chat_id,
                "text": text[:4096],
            }).encode()
            req = urllib.request.Request(url, data=data, method="POST")
            with urllib.request.urlopen(req, timeout=10) as resp:
                return resp.status == 200
        except Exception as e:
            log.warning(f"Telegram send failed: {e}")
            return False

    def _format_briefing(self, briefing: dict) -> str:
        """Format a briefing dict as a Telegram message."""
        h = briefing.get("health", {})
        lines = [
            f"Morning Briefing — {briefing.get('date', '?')}",
            f"Health: {h.get('checks_passed', 0)}/{h.get('checks_run', 0)} checks passed",
        ]
        actions = briefing.get("action_items", [])
        if actions:
            lines.append("Action items:")
            for a in actions[:5]:
                lines.append(f"  [{a.get('priority', '?')}] {a.get('item', '?')}")
        return "\n".join(lines)


def main():
    """Entry point for standalone execution."""
    import argparse
    parser = argparse.ArgumentParser(description="AgentHarness Inbox Watcher")
    parser.add_argument("--inbox-dir", required=True, help="Path to AgentHarness data directory")
    parser.add_argument("--interval", type=int, default=60, help="Check interval in seconds")
    parser.add_argument("--once", action="store_true", help="Run once and exit")
    args = parser.parse_args()

    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")

    if not token or not chat_id:
        print("ERROR: Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID environment variables")
        print("These are YOUR agent's credentials, not AgentHarness's.")
        sys.exit(1)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s")

    watcher = InboxWatcher(
        inbox_dir=args.inbox_dir,
        telegram_token=token,
        telegram_chat_id=chat_id,
    )

    if args.once:
        result = watcher.tick()
        print(f"Delivered: {result}")
    else:
        watcher.run_loop(interval=args.interval)


if __name__ == "__main__":
    main()
