#!/bin/bash
# Auto-generated by service wiring — backs up all registered Docker volumes
# Run via cron: 0 2 * * * bash /home/rohit/agentharness/scripts/backup_volumes.sh
set -euo pipefail

BACKUP_DIR="/mnt/usb/backups/docker-volumes/$(date +%Y-%m-%d)"
mkdir -p "$BACKUP_DIR"

BACKED_UP=0
FAILED=0

# gitea
if [ -d "/home/rohit/openclaw/data/gitea" ]; then
    echo "Backing up gitea: /home/rohit/openclaw/data/gitea"
    tar czf "$BACKUP_DIR/gitea_gitea.tar.gz" -C "/home/rohit/openclaw/data/gitea" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# homarr
if [ -d "/var/lib/docker/volumes/homarr_homarr-config/_data" ]; then
    echo "Backing up homarr: /var/lib/docker/volumes/homarr_homarr-config/_data"
    tar czf "$BACKUP_DIR/homarr_data.tar.gz" -C "/var/lib/docker/volumes/homarr_homarr-config/_data" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# litellm
if [ -d "/home/rohit/litellm/config.yaml" ]; then
    echo "Backing up litellm: /home/rohit/litellm/config.yaml"
    tar czf "$BACKUP_DIR/litellm_config.yaml.tar.gz" -C "/home/rohit/litellm/config.yaml" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# nginx-proxy-manager
if [ -d "/var/lib/docker/volumes/npm_npm-data/_data" ]; then
    echo "Backing up nginx-proxy-manager: /var/lib/docker/volumes/npm_npm-data/_data"
    tar czf "$BACKUP_DIR/nginx-proxy-manager_data.tar.gz" -C "/var/lib/docker/volumes/npm_npm-data/_data" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# paperless
if [ -d "/home/rohit/openclaw/data/paperless/data" ]; then
    echo "Backing up paperless: /home/rohit/openclaw/data/paperless/data"
    tar czf "$BACKUP_DIR/paperless_data.tar.gz" -C "/home/rohit/openclaw/data/paperless/data" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# portainer
if [ -d "/var/lib/docker/volumes/portainer_data/_data" ]; then
    echo "Backing up portainer: /var/lib/docker/volumes/portainer_data/_data"
    tar czf "$BACKUP_DIR/portainer_data.tar.gz" -C "/var/lib/docker/volumes/portainer_data/_data" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# stump
if [ -d "/home/rohit/.stump" ]; then
    echo "Backing up stump: /home/rohit/.stump"
    tar czf "$BACKUP_DIR/stump_stump.tar.gz" -C "/home/rohit/.stump" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# uptime-kuma
if [ -d "/opt/uptime-kuma/data" ]; then
    echo "Backing up uptime-kuma: /opt/uptime-kuma/data"
    tar czf "$BACKUP_DIR/uptime-kuma_data.tar.gz" -C "/opt/uptime-kuma/data" . 2>/dev/null && BACKED_UP=$((BACKED_UP+1)) || FAILED=$((FAILED+1))
fi

# Cleanup: keep last 7 days of backups
find "/mnt/usb/backups/docker-volumes" -maxdepth 1 -type d -mtime +7 -exec rm -rf {} \; 2>/dev/null || true

echo "Backup complete: $BACKED_UP succeeded, $FAILED failed"
