#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# integrate_chaguli.sh — Add AgentHarness tools to Chaguli's tool system
#
# Generates agentharness_tools.py with new tool schemas and implementations.
# Patches tools.py to import and merge them (preserving existing tools).
# Creates new domain modules for AgentHarness capabilities.
#
# Follows the exact same pattern as existing tools.py:
#   - TOOL_SCHEMAS list (OpenAI function calling format)
#   - dispatch() function
#   - _tool_* implementation functions
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

[ -f "${AH_DATA_DIR}/chaguli_paths.env" ] && source "${AH_DATA_DIR}/chaguli_paths.env"

CHAGULI_DIR="${CHAGULI_APP_DIR:-}"
AGENTHARNESS_SCRIPTS="${SCRIPT_DIR}"

main() {
    log_header "Chaguli Integration"

    if [ -z "${CHAGULI_DIR}" ] || [ ! -f "${CHAGULI_DIR}/tools.py" ]; then
        log_error "Chaguli app directory not found. Run discover_chaguli.sh first."
        return 1
    fi

    log_info "Chaguli app: ${CHAGULI_DIR}"
    log_info "AgentHarness scripts: ${AGENTHARNESS_SCRIPTS}"

    # --- Step 1: Create agentharness_tools.py ---
    log_info "Creating agentharness_tools.py..."

    local tools_file="${CHAGULI_DIR}/agentharness_tools.py"

    # Check if it already exists (don't overwrite user modifications)
    if [ -f "${tools_file}" ] && ! grep -q "Auto-generated by AgentHarness" "${tools_file}"; then
        log_info "agentharness_tools.py exists and was user-modified — skipping"
    else
        cat > "${tools_file}" << 'TOOLSPY'
#!/usr/bin/env python3
"""
AgentHarness tools for Chaguli — Auto-generated by AgentHarness installer.
Adds infrastructure management capabilities to Chaguli's tool system.

These tools call AgentHarness shell scripts and return results.
"""
import logging
import subprocess
import os

log = logging.getLogger("agentharness_tools")

SCRIPTS_DIR = os.environ.get("AH_SCRIPTS_DIR", os.environ.get("AGENTHARNESS_SCRIPTS", "/opt/agentharness/scripts"))

# ── Tool schema definitions ───────────────────────────────────────────────────

TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "deploy_repo",
            "description": "Deploy a GitHub repository to the homelab. Clones, detects setup method, installs, and wires up the service. Use when asked to deploy, install, or set up a GitHub repo.",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "GitHub repository URL",
                    }
                },
                "required": ["url"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_benchmark",
            "description": "Benchmark LLM models and inference engines. Compares all available models, generates a comparison chart, and can auto-switch to the best configuration. Use when asked about LLM performance, benchmarks, or model comparison.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "cleanup_system",
            "description": "Clean up unused Docker images, containers, volumes, packages, logs, and temp files. Frees disk space. Use when asked to clean up, free space, or when disk is getting full.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "check_trends",
            "description": "Show resource usage trends and predict when thresholds will be hit. Projects disk, RAM, and swap usage forward. Use when asked about trends, projections, or 'when will disk be full?'",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "check_updates",
            "description": "Check if any running Docker containers have newer image versions available. Use when asked about updates, new versions, or 'is anything outdated?'",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_security_audit",
            "description": "Run a security audit of the homelab — check exposed ports, file permissions, Docker socket access, SSH config. Use when asked about security, vulnerabilities, or hardening.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "diagnose_system",
            "description": "Run the AgentHarness doctor to diagnose what's wrong with the system. Checks all components and suggests fixes. Use when something is broken and you need a systematic diagnosis.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_new_tools",
            "description": "Search the web for new LLM models, inference optimizations, self-hosted tools, and homelab improvements. Use when asked 'anything new?', 'what's the latest?', or to find new tools.",
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "Optional specific topic to search for. If empty, searches all interest areas.",
                    }
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_backup",
            "description": "Run a backup of homelab configs, Chaguli state, and system data to the USB drive. Use when asked to backup, or proactively when it's been too long since last backup.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
]


# ── Tool dispatcher ───────────────────────────────────────────────────────────

def dispatch(tool_name: str, tool_args: dict) -> str:
    """Execute an AgentHarness tool. Returns a string result."""
    try:
        handler = {
            "deploy_repo": _tool_deploy_repo,
            "run_benchmark": _tool_run_benchmark,
            "cleanup_system": _tool_cleanup_system,
            "check_trends": _tool_check_trends,
            "check_updates": _tool_check_updates,
            "run_security_audit": _tool_run_security_audit,
            "diagnose_system": _tool_diagnose_system,
            "search_new_tools": _tool_search_new_tools,
            "run_backup": _tool_run_backup,
        }.get(tool_name)

        if handler:
            return handler(tool_args)
        return f"Unknown AgentHarness tool: {tool_name}"
    except Exception as e:
        log.error(f"AgentHarness tool {tool_name} failed: {e}")
        return f"Tool {tool_name} error: {e}"


def _run_script(script_name: str, args: str = "", timeout: int = 300) -> str:
    """Run an AgentHarness script and return output."""
    script_path = os.path.join(SCRIPTS_DIR, script_name)
    if not os.path.exists(script_path):
        return f"Script not found: {script_path}"

    try:
        result = subprocess.run(
            f"bash {script_path} {args}",
            shell=True, capture_output=True, text=True, timeout=timeout,
            env={**os.environ, "TERM": "dumb"}  # Disable color codes
        )
        output = result.stdout.strip()
        if result.returncode != 0 and result.stderr:
            output += f"\n\nErrors:\n{result.stderr.strip()[-500:]}"
        # Truncate for Telegram
        if len(output) > 3000:
            output = output[:2900] + "\n\n... (truncated, see full output in " + os.environ.get("AH_REPORTS_DIR", "/opt/agentharness/reports") + "/)"
        return output or "Completed (no output)"
    except subprocess.TimeoutExpired:
        return f"{script_name} timed out after {timeout}s. It may still be running in the background."


# ── Tool implementations ──────────────────────────────────────────────────────

def _tool_deploy_repo(args: dict) -> str:
    url = args.get("url", "")
    if not url:
        return "No GitHub URL provided. Usage: deploy_repo(url='https://github.com/user/repo')"
    return _run_script("github_deploy.sh", url, timeout=600)


def _tool_run_benchmark(args: dict) -> str:
    return _run_script("benchmark.sh", timeout=1800)


def _tool_cleanup_system(args: dict) -> str:
    return _run_script("cleanup.sh", timeout=300)


def _tool_check_trends(args: dict) -> str:
    return _run_script("trend_projector.sh", timeout=60)


def _tool_check_updates(args: dict) -> str:
    return _run_script("update_watcher.sh", timeout=120)


def _tool_run_security_audit(args: dict) -> str:
    return _run_script("security_audit.sh", timeout=120)


def _tool_diagnose_system(args: dict) -> str:
    return _run_script("doctor.sh", timeout=120)


def _tool_search_new_tools(args: dict) -> str:
    topic = args.get("topic", "")
    if topic:
        return _run_script("weekly_optimize.sh", timeout=600)
    return _run_script("weekly_optimize.sh", timeout=600)


def _tool_run_backup(args: dict) -> str:
    return _run_script("backup.sh", timeout=600)
TOOLSPY

        log_ok "Created: ${tools_file}"
    fi

    # --- Step 2: Patch tools.py to import AgentHarness tools ---
    log_info "Patching tools.py to include AgentHarness tools..."

    local tools_py="${CHAGULI_DIR}/tools.py"

    if grep -q "agentharness_tools" "${tools_py}"; then
        log_info "tools.py already imports agentharness_tools — skipping"
    else
        # Add import at the top (after existing imports)
        local patch_import="
# ── AgentHarness integration (auto-added by AgentHarness installer) ───────────
try:
    from agentharness_tools import TOOL_SCHEMAS as AH_TOOL_SCHEMAS
    from agentharness_tools import dispatch as ah_dispatch
    TOOL_SCHEMAS.extend(AH_TOOL_SCHEMAS)
except ImportError:
    AH_TOOL_SCHEMAS = []
    ah_dispatch = None
"
        # Add after the TOOL_SCHEMAS list closing bracket
        # Find the line with the closing ] of TOOL_SCHEMAS
        python3 -c "
content = open('${tools_py}').read()

# Find where TOOL_SCHEMAS ends (the last ] before the dispatch function)
import re

# Add the import block after the TOOL_SCHEMAS closing
marker = '# ── Tool dispatcher'
if marker in content and 'agentharness_tools' not in content:
    patch = '''
# ── AgentHarness integration (auto-added by AgentHarness installer) ───────────
try:
    from agentharness_tools import TOOL_SCHEMAS as AH_TOOL_SCHEMAS
    from agentharness_tools import dispatch as ah_dispatch
    TOOL_SCHEMAS.extend(AH_TOOL_SCHEMAS)
except ImportError:
    AH_TOOL_SCHEMAS = []
    ah_dispatch = None

'''
    content = content.replace(marker, patch + marker)

    # Also patch the dispatch function to try agentharness tools
    old_dispatch_else = '        else:\n            return f\"Unknown tool: {tool_name}\"'
    new_dispatch_else = '''        elif ah_dispatch:
            return ah_dispatch(tool_name, tool_args)
        else:
            return f\"Unknown tool: {tool_name}\"'''
    content = content.replace(old_dispatch_else, new_dispatch_else)

    open('${tools_py}', 'w').write(content)
    print('Patched tools.py')
else:
    print('tools.py already patched or marker not found')
" 2>/dev/null

        if grep -q "agentharness_tools" "${tools_py}"; then
            log_ok "tools.py patched successfully"
        else
            log_warn "Could not auto-patch tools.py. Manual integration needed."
            log_info "Add to tools.py:"
            echo "  from agentharness_tools import TOOL_SCHEMAS as AH_TOOL_SCHEMAS, dispatch as ah_dispatch"
            echo "  TOOL_SCHEMAS.extend(AH_TOOL_SCHEMAS)"
            echo "  # In dispatch(), add: elif ah_dispatch: return ah_dispatch(tool_name, tool_args)"
        fi
    fi

    # --- Step 3: Add AGENTHARNESS_SCRIPTS env var to Chaguli's container ---
    log_info "Checking if Chaguli container has AGENTHARNESS_SCRIPTS env..."

    local has_env
    has_env=$(docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "${CHAGULI_CONTAINER:-chaguli}" 2>/dev/null | grep "AGENTHARNESS_SCRIPTS" || true)

    if [ -z "${has_env}" ]; then
        log_warn "Chaguli container needs AGENTHARNESS_SCRIPTS env var."
        log_info "Add to your Chaguli docker-compose or docker run:"
        echo "  -e AH_SCRIPTS_DIR=${AH_SCRIPTS_DIR}"
        echo "  -v ${AH_SCRIPTS_DIR}:${AH_SCRIPTS_DIR}:ro"
        echo ""
        log_info "Then restart Chaguli: docker restart ${CHAGULI_CONTAINER:-chaguli}"
    fi

    # --- Step 4: Update config.yml with AgentHarness settings ---
    local config_yml="${CHAGULI_DIR}/config.yml"
    if [ -f "${config_yml}" ] && ! grep -q "agentharness" "${config_yml}"; then
        log_info "Appending AgentHarness config to config.yml..."
        cat >> "${config_yml}" << 'YAMLCFG'

# ── AgentHarness integration (auto-added) ─────────────────────────────────────
agentharness:
  scripts_dir: "auto"  # Resolved from state.json at runtime
  reports_dir: "auto"  # Resolved from state.json at runtime
  # New tools added: deploy_repo, run_benchmark, cleanup_system, check_trends,
  #                  check_updates, run_security_audit, diagnose_system,
  #                  search_new_tools, run_backup
  guardrails:
    # These tools run immediately (NOTIFY tier — safe, non-destructive)
    notify_tools:
      - check_trends
      - check_updates
      - diagnose_system
      - search_new_tools
    # These require confirmation before executing
    confirm_tools:
      - deploy_repo
      - cleanup_system
      - run_benchmark
      - run_backup
      - run_security_audit
YAMLCFG
        log_ok "config.yml updated"
    else
        log_info "config.yml already has agentharness section — skipping"
    fi

    # --- Summary ---
    log_header "Integration Complete"
    echo ""
    echo "  New tools added to Chaguli:"
    echo "    - deploy_repo        'Deploy this GitHub repo'"
    echo "    - run_benchmark      'Benchmark the LLM models'"
    echo "    - cleanup_system     'Clean up disk space'"
    echo "    - check_trends       'When will disk be full?'"
    echo "    - check_updates      'Any container updates?'"
    echo "    - run_security_audit 'Run a security check'"
    echo "    - diagnose_system    'What's broken?'"
    echo "    - search_new_tools   'Anything new this week?'"
    echo "    - run_backup         'Backup everything'"
    echo ""
    echo "  To activate, restart Chaguli:"
    echo "    docker restart ${CHAGULI_CONTAINER:-chaguli}"
    echo ""
    echo "  NOTE: Chaguli's container needs these mounts for full functionality:"
    echo "    -v ${AH_SCRIPTS_DIR}:${AH_SCRIPTS_DIR}:ro"
    echo "    -e AH_SCRIPTS_DIR=${AH_SCRIPTS_DIR}"
    echo ""
}

main "$@"
