#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# openclaw_sync.sh — Sync service registry → OpenClaw skills + AGENTS.md
#
# For each service in the registry:
#   1. Generates a SKILL.md file (tells Chaguli how to interact with the service)
#   2. Drops it into ~/.openclaw/workspace/skills/<service>/
#   3. Updates ~/.openclaw/workspace/AGENTS.md with full service catalog
#
# OpenClaw hot-reloads skills — Chaguli gains capabilities immediately.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

REGISTRY="/opt/agentharness/service_registry.json"
OPENCLAW_PATHS="/opt/agentharness/openclaw_paths.env"

[ -f /opt/agentharness/.env ] && source /opt/agentharness/.env

# =============================================================================
# Discover OpenClaw paths — never hardcode
# =============================================================================
load_openclaw_paths() {
    # If discovery has been run, use those paths
    if [ -f "${OPENCLAW_PATHS}" ]; then
        source "${OPENCLAW_PATHS}"
    else
        # Run discovery if paths file doesn't exist
        log_info "OpenClaw paths not yet discovered. Running discovery..."
        bash "${SCRIPT_DIR}/discover_automations.sh" 2>/dev/null || true
        [ -f "${OPENCLAW_PATHS}" ] && source "${OPENCLAW_PATHS}"
    fi

    # Validate we found the essentials
    if [ -z "${OPENCLAW_SKILLS_DIR:-}" ]; then
        log_error "Could not find OpenClaw skills directory."
        log_info "Ensure OpenClaw is installed and run: bash scripts/discover_automations.sh"
        return 1
    fi

    if [ -z "${OPENCLAW_AGENTS_MD:-}" ]; then
        log_warn "AGENTS.md not found. Will look for it in workspace."
        # Try workspace root
        if [ -n "${OPENCLAW_WORKSPACE:-}" ]; then
            OPENCLAW_AGENTS_MD="${OPENCLAW_WORKSPACE}/AGENTS.md"
        fi
    fi

    SKILLS_DIR="${OPENCLAW_SKILLS_DIR}"
    AGENTS_FILE="${OPENCLAW_AGENTS_MD:-}"

    log_info "Skills directory: ${SKILLS_DIR}"
    log_info "AGENTS.md: ${AGENTS_FILE:-not found}"
}

# Shorthand
load_openclaw_paths || exit 1

# =============================================================================
# Generate a SKILL.md for a service
# =============================================================================
generate_skill() {
    local service_json="$1"

    python3 << PYEOF
import json, os

svc = json.loads('''${service_json}''')
container = svc['container']

# Check if a skill for this service already exists (user-created, not ours)
safe_name = container.replace(' ', '-').lower()
skill_dir = "${SKILLS_DIR}/homelab-" + safe_name
skill_path = os.path.join(skill_dir, "SKILL.md")

# Also check for user-created skill with same service name (without homelab- prefix)
user_skill = os.path.join("${SKILLS_DIR}", safe_name, "SKILL.md")
if os.path.exists(user_skill):
    # User has their own skill for this service — don't overwrite
    print(f"{container}: User skill exists at {user_skill} — skipping")
    exit(0)

# If our managed skill exists, check if service has changed
if os.path.exists(skill_path):
    existing = open(skill_path).read()
    if "Auto-generated by AgentHarness" not in existing:
        # User has modified this skill — don't overwrite
        print(f"{container}: Skill modified by user — skipping")
        exit(0)
category = svc.get('category', 'other')
capabilities = svc.get('chaguli_capabilities', [])
endpoints = svc.get('endpoints', [])

os.makedirs(skill_dir, exist_ok=True)

# Find key endpoints
api_endpoints = [e for e in endpoints if e.get('is_api')]
health_endpoints = [e for e in endpoints if e.get('is_health')]
json_endpoints = [e for e in endpoints if e.get('is_json')]

# Build SKILL.md
skill = f"""---
name: homelab-{safe_name}
description: Interact with {container} ({category}) on the homelab
requires:
  binaries: ["curl"]
---

# {container} ({category.title()})

You can interact with the **{container}** service on this homelab.

"""

    # Health check
    if health_endpoints:
        he = health_endpoints[0]
        skill += f"""## Health Check

To check if {container} is running:

\`\`\`bash
curl -sf {he['url']}
\`\`\`

If this returns an error or times out, the service is down. Try restarting:

\`\`\`bash
docker restart {container}
\`\`\`

"""

    # API queries
    if json_endpoints:
        skill += f"## Query {container}\n\n"
        for ep in json_endpoints[:5]:
            skill += f"**{ep['path']}** (HTTP {ep.get('http_code', '?')}):\n"
            skill += f"\`\`\`bash\ncurl -sf {ep['url']}\n\`\`\`\n\n"

    # Service-specific instructions
    cap_set = set(capabilities)

    if 'dns_stats' in cap_set:
        api_php = next((e['url'] for e in endpoints if 'api.php' in e.get('path', '')), None)
        if api_php:
            skill += f"""## DNS Statistics

Get Pi-hole summary:
\`\`\`bash
curl -sf "{api_php}?summary"
\`\`\`

Get top blocked domains:
\`\`\`bash
curl -sf "{api_php}?topItems=10"
\`\`\`

"""

    if 'manage_containers' in cap_set:
        skill += f"""## Container Management (via Portainer)

List all containers:
\`\`\`bash
curl -sf "{next((e['url'] for e in endpoints if 'containers' in e.get('path', '') or 'endpoints' in e.get('path', '')), 'http://localhost:9000/api/endpoints')}"
\`\`\`

Note: Portainer API may require an API key header: `-H "X-API-Key: $PORTAINER_API_KEY"`

"""

    if 'web_search' in cap_set:
        search_url = next((e['url'].split('?')[0] for e in endpoints if 'search' in e.get('path', '')), None)
        if search_url:
            skill += f"""## Web Search

Search the web using local SearXNG:
\`\`\`bash
curl -sf "{search_url}?q=YOUR_QUERY&format=json"
\`\`\`

Use this for looking up Docker issues, troubleshooting errors, or finding documentation.

"""

    if 'trigger_workflows' in cap_set or 'list_workflows' in cap_set:
        skill += f"""## n8n Workflows

List all workflows:
\`\`\`bash
curl -sf "http://localhost:5678/api/v1/workflows" -H "X-N8N-API-KEY: $N8N_API_KEY"
\`\`\`

"""

    if 'manage_proxies' in cap_set:
        skill += f"""## Nginx Proxy Manager

List proxy hosts:
\`\`\`bash
curl -sf "{next((e['url'] for e in endpoints if 'proxy-hosts' in e.get('path', '')), 'http://localhost:81/api/nginx/proxy-hosts')}"
\`\`\`

"""

    if 'media_info' in cap_set:
        skill += f"""## Media Info

Get public server info:
\`\`\`bash
curl -sf "{next((e['url'] for e in endpoints if 'Public' in e.get('path', '') or 'Info' in e.get('path', '')), endpoints[0]['url'] if endpoints else 'http://localhost:8096')}"
\`\`\`

"""

    if 'search_shows' in cap_set or 'search_movies' in cap_set:
        skill += f"""## Arr Stack

Check system status:
\`\`\`bash
curl -sf "{next((e['url'] for e in endpoints if 'status' in e.get('path', '')), endpoints[0]['url'] if endpoints else '#')}"
\`\`\`

Note: Arr APIs typically need an API key parameter: `?apikey=YOUR_KEY`

"""

    # Docker management (always available)
    skill += f"""## Docker Management

Restart this service:
\`\`\`bash
docker restart {container}
\`\`\`

View recent logs:
\`\`\`bash
docker logs --tail 50 {container}
\`\`\`

Check resource usage:
\`\`\`bash
docker stats --no-stream {container}
\`\`\`

"""

    # Write the skill file
    skill_path = os.path.join(skill_dir, "SKILL.md")
    with open(skill_path, 'w') as f:
        f.write(skill)

    method_count = skill.count('## ') - 1  # subtract the title
    print(f"{container}: {method_count} sections, written to {skill_path}")
PYEOF
}

# =============================================================================
# Generate AGENTS.md — Chaguli's master system prompt
# =============================================================================
generate_agents_section() {
    if [ -z "${AGENTS_FILE}" ]; then
        log_warn "AGENTS.md path not discovered. Skipping."
        return 0
    fi

    log_info "Updating AGENTS.md (appending managed section)..."

    # Generate the AgentHarness-managed section
    local managed_section
    managed_section=$(python3 << PYEOF
import json
from datetime import datetime

reg = json.load(open("${REGISTRY}"))

# This is a MANAGED SECTION — delimited by markers so we can update it
# without touching the rest of AGENTS.md
section = """
<!-- AGENTHARNESS:BEGIN — Auto-managed by AgentHarness. Do not edit between these markers. -->
## Homelab Service Registry

**Last synced:** {updated}
**Services:** {total} | **API Endpoints:** {endpoints} | **Capabilities:** {caps}

""".format(
    updated=datetime.now().strftime('%Y-%m-%d %H:%M'),
    total=reg['total_services'],
    endpoints=reg['total_api_endpoints'],
    caps=', '.join(reg['all_capabilities'])
)

# Group by category
cats = {}
for svc in reg['services']:
    cat = svc.get('category', 'other')
    cats.setdefault(cat, []).append(svc)

for cat in sorted(cats.keys()):
    section += f"### {cat.title()}\n"
    for svc in cats[cat]:
        container = svc['container']
        caps = svc.get('chaguli_capabilities', [])
        health = [e for e in svc.get('endpoints', []) if e.get('is_health')]
        caps_str = ", ".join(caps) if caps else "docker management only"
        health_url = health[0]['url'] if health else "N/A"
        section += f"- **{container}**: {caps_str}\n"
        if health_url != "N/A":
            section += f"  - Health: \`curl -sf {health_url}\`\n"
    section += "\n"

if reg.get('mcp_servers'):
    section += f"### MCP Servers ({reg['total_mcp_servers']})\n"
    for mcp in reg['mcp_servers']:
        name = mcp.get('server_info', {}).get('name', f"MCP on port {mcp.get('port')}")
        tools = mcp.get('tools', [])
        section += f"- **{name}**: {len(tools)} tools\n"
        for t in tools[:10]:
            section += f"  - \`{t.get('name', '?')}\`: {t.get('description', '')[:80]}\n"
    section += "\n"

section += """### AgentHarness Maintenance

Run these via exec tool:
- Check health: \`bash /opt/agentharness/scripts/validate.sh\`
- Cleanup: \`bash /opt/agentharness/scripts/cleanup.sh\`
- Deploy GitHub repo: \`bash /opt/agentharness/scripts/github_deploy.sh <url>\`
- Re-benchmark LLMs: \`bash /opt/agentharness/scripts/benchmark.sh\`
- View reports: \`ls -lt /opt/agentharness/reports/ | head -10\`

<!-- AGENTHARNESS:END -->"""

print(section)
PYEOF
)

    if [ ! -f "${AGENTS_FILE}" ]; then
        # File doesn't exist yet — create with just our section
        echo "${managed_section}" > "${AGENTS_FILE}"
        log_ok "Created AGENTS.md with service registry"
    elif grep -q "AGENTHARNESS:BEGIN" "${AGENTS_FILE}"; then
        # Our section already exists — replace it
        python3 -c "
import re
content = open('${AGENTS_FILE}').read()
new_section = '''${managed_section}'''
# Replace everything between the markers
pattern = r'<!-- AGENTHARNESS:BEGIN.*?<!-- AGENTHARNESS:END -->'
updated = re.sub(pattern, new_section.strip(), content, flags=re.DOTALL)
open('${AGENTS_FILE}', 'w').write(updated)
print('Updated existing AgentHarness section in AGENTS.md')
" 2>/dev/null
        log_ok "Updated AgentHarness section in existing AGENTS.md"
    else
        # File exists but doesn't have our section — append
        echo "" >> "${AGENTS_FILE}"
        echo "${managed_section}" >> "${AGENTS_FILE}"
        log_ok "Appended AgentHarness section to existing AGENTS.md"
    fi
}

# =============================================================================
# Generate a homelab management meta-skill
# =============================================================================
generate_meta_skill() {
    log_info "Generating AgentHarness meta-skill..."

    local meta_dir="${SKILLS_DIR}/agentharness"
    mkdir -p "${meta_dir}"

    cat > "${meta_dir}/SKILL.md" << 'SKILL'
---
name: agentharness
description: Run AgentHarness maintenance scripts for the homelab
requires:
  binaries: ["bash"]
---

# AgentHarness — Homelab Management

You have access to AgentHarness scripts for homelab maintenance.

## Available Commands

### Check system health
```bash
bash /opt/agentharness/scripts/validate.sh
```

### Run benchmarks on LLM models
```bash
bash /opt/agentharness/scripts/benchmark.sh
```

### Clean up unused Docker images, volumes, and packages
```bash
bash /opt/agentharness/scripts/cleanup.sh
```

### Search for new LLM models and optimization techniques
```bash
bash /opt/agentharness/scripts/weekly_optimize.sh
```

### Deploy a GitHub repo
```bash
bash /opt/agentharness/scripts/github_deploy.sh https://github.com/user/repo
```

### Refresh the service registry (after deploying new services)
```bash
bash /opt/agentharness/scripts/service_registry.sh
```

### Sync skills to OpenClaw (after registry refresh)
```bash
bash /opt/agentharness/scripts/openclaw_sync.sh
```

### View latest reports
```bash
ls -lt /opt/agentharness/reports/ | head -10
```

### View current best LLM configuration
```bash
cat /opt/agentharness/best_config.env
```

### View the scheduler state
```bash
cat /opt/agentharness/scheduler_state.json
```

## When to Use

- User asks to "clean up" or "free disk space" → run cleanup.sh
- User asks to "deploy" or "install" a GitHub repo → run github_deploy.sh
- User asks about LLM performance → run benchmark.sh or show best_config.env
- User asks about system health → run validate.sh
- After deploying anything new → run service_registry.sh then openclaw_sync.sh
SKILL

    log_ok "Meta-skill: ${meta_dir}/SKILL.md"
}

# =============================================================================
# Main
# =============================================================================
main() {
    log_header "OpenClaw Sync"

    # Ensure registry is fresh
    if [ ! -f "${REGISTRY}" ] || \
       [ "$(find "${REGISTRY}" -mmin +30 2>/dev/null)" ]; then
        log_info "Registry stale or missing. Running service discovery..."
        bash "${SCRIPT_DIR}/service_registry.sh"
    fi

    # Skills directory must exist (discovered by load_openclaw_paths)
    if [ ! -d "${SKILLS_DIR}" ]; then
        log_warn "Skills directory not found at ${SKILLS_DIR}"
        log_info "Creating it..."
        mkdir -p "${SKILLS_DIR}"
    fi

    # Generate skills for each service with capabilities
    local skills_generated=0

    python3 -c "
import json
reg = json.load(open('${REGISTRY}'))
for svc in reg['services']:
    if svc.get('chaguli_capabilities') or svc.get('endpoints'):
        print(json.dumps(svc))
" 2>/dev/null | while IFS= read -r service_json; do
        generate_skill "${service_json}"
        ((skills_generated++))
    done

    # Generate meta-skill for AgentHarness itself
    generate_meta_skill

    # Update AGENTS.md (append/update managed section, preserve existing content)
    generate_agents_section

    # Summary
    local total_skills
    total_skills=$(find "${SKILLS_DIR}" -name "SKILL.md" 2>/dev/null | wc -l)

    log_header "Sync Complete"
    echo ""
    echo "  Skills generated: ${total_skills}"
    echo "  Skills directory: ${SKILLS_DIR}/"
    echo "  AGENTS.md: ${AGENTS_FILE:-not configured}"
    echo ""
    echo "  OpenClaw hot-reloads skills — Chaguli has the new capabilities now."
    echo ""

    # List generated skills
    if command -v openclaw &>/dev/null; then
        log_info "Installed skills:"
        openclaw skills list 2>/dev/null || find "${SKILLS_DIR}" -name "SKILL.md" -exec dirname {} \; | xargs -I{} basename {}
    else
        log_info "Skills:"
        find "${SKILLS_DIR}" -name "SKILL.md" -exec dirname {} \; | xargs -I{} basename {} | sort
    fi
}

main "$@"
