#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# self_update.sh — Pull latest AgentHarness from git and apply changes
#
# Safe update: pulls changes, re-copies skills to OpenClaw, re-installs
# registry config, but NEVER overwrites .env, discovered paths, or state.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

INSTALL_DIR="${AH_INSTALL_DIR}"
REPO_DIR="${INSTALL_DIR}/repo"

[ -f "${AH_DATA_DIR}/chaguli_paths.env" ] && source "${AH_DATA_DIR}/chaguli_paths.env"

main() {
    log_header "AgentHarness Self-Update"

    # Find the git repo
    local git_dir=""
    for candidate in "${REPO_DIR}" "${INSTALL_DIR}" "$(dirname "${SCRIPT_DIR}")"; do
        if [ -d "${candidate}/.git" ]; then
            git_dir="${candidate}"
            break
        fi
    done

    if [ -z "${git_dir}" ]; then
        log_error "No git repo found. Update manually by copying files."
        return 1
    fi

    cd "${git_dir}"

    # Check for updates
    local current_hash
    current_hash=$(git rev-parse --short HEAD)
    log_info "Current version: ${current_hash}"

    git fetch --quiet 2>/dev/null || {
        log_warn "git fetch failed — are you online?"
        return 1
    }

    local behind
    behind=$(git rev-list --count HEAD..@{u} 2>/dev/null || echo "0")

    if [ "${behind}" = "0" ]; then
        log_ok "Already up to date"
        return 0
    fi

    log_info "${behind} new commit(s) available"

    # Show what changed
    echo ""
    git log --oneline HEAD..@{u} | head -10
    echo ""

    # Pull
    git pull --ff-only || {
        log_error "Pull failed (merge conflict?). Resolve manually in ${git_dir}"
        return 1
    }

    local new_hash
    new_hash=$(git rev-parse --short HEAD)
    log_ok "Updated: ${current_hash} → ${new_hash}"

    # Re-copy scripts to ${AH_SCRIPTS_DIR}/
    if [ "${git_dir}" != "${INSTALL_DIR}" ]; then
        log_info "Syncing scripts..."
        rsync -a --exclude='.git' --exclude='.env' \
            "${git_dir}/scripts/" "${INSTALL_DIR}/scripts/" 2>/dev/null || \
            cp -r "${git_dir}/scripts/"* "${INSTALL_DIR}/scripts/"
    fi

    # Re-copy skills to OpenClaw (only new ones, never overwrite)
    if [ -n "${OPENCLAW_SKILLS_DIR:-}" ] && [ -d "${git_dir}/config/skills" ]; then
        log_info "Syncing new skills to OpenClaw..."
        for skill_dir in "${git_dir}/config/skills"/*/; do
            local skill_name
            skill_name=$(basename "${skill_dir}")
            local target="${OPENCLAW_SKILLS_DIR}/${skill_name}"
            if [ ! -d "${target}" ]; then
                cp -r "${skill_dir}" "${target}"
                log_ok "New skill installed: ${skill_name}"
            else
                # Only update auto-generated skills (check for our marker)
                if grep -q "Auto-generated by AgentHarness" "${target}/SKILL.md" 2>/dev/null; then
                    cp -r "${skill_dir}" "${target}"
                    log_info "Updated managed skill: ${skill_name}"
                fi
            fi
        done
    fi

    # Update registry config (merge, don't overwrite)
    if [ -f "${git_dir}/config/harness_registry.yaml" ]; then
        local dest="${INSTALL_DIR}/config/harness_registry.yaml"
        if [ ! -f "${dest}" ]; then
            cp "${git_dir}/config/harness_registry.yaml" "${dest}"
            log_ok "Registry config installed"
        else
            log_info "Registry config exists — not overwriting (merge manually if needed)"
        fi
    fi

    # Make scripts executable
    chmod +x "${INSTALL_DIR}/scripts/"*.sh 2>/dev/null || true

    log_header "Update Complete"
    echo "  ${current_hash} → ${new_hash} (${behind} commits)"
    echo ""
    echo "  Run 'ah-doctor' to verify everything is healthy"
}

main "$@"
